# building app and required component for running the app
version: '3'
services:
  database:
    build: docker/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
  web:
    build: docker/nginx
    ports:
      - "80:80"
    # we have configured our nginx container to have its webroot /var/www/public
    # so we have to mount our project [project name here] folder to /var/www
    # we already have "public" folder in our project
    volumes:
      - ./laravel_blog_FGT:/var/www
    links:
      - php
    depends_on:
      - php
  php:
    build: docker/php
    volumes:
      - ./laravel_blog_FGT:/var/www
    expose:
      - "9000"
